export const GET_WEATHER = "COMMAND/GET_WEATHER_FOR_LAT_LNG";
export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const WEATHER_ID_RECEIVED = "EVENT/WEATHER_ID_RECEIVED";
export const GET_METRIC_DATA = "GET_METRIC_DATA"
